/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accesstoken implements Serializable {

    private static final long serialVersionUID = 1944171897;

    private String        accesstoken;
    private LocalDateTime expirytime;
    private String        accountnum;

    public Accesstoken() {}

    public Accesstoken(Accesstoken value) {
        this.accesstoken = value.accesstoken;
        this.expirytime = value.expirytime;
        this.accountnum = value.accountnum;
    }

    public Accesstoken(
        String        accesstoken,
        LocalDateTime expirytime,
        String        accountnum
    ) {
        this.accesstoken = accesstoken;
        this.expirytime = expirytime;
        this.accountnum = accountnum;
    }

    public String getAccesstoken() {
        return this.accesstoken;
    }

    public void setAccesstoken(String accesstoken) {
        this.accesstoken = accesstoken;
    }

    public LocalDateTime getExpirytime() {
        return this.expirytime;
    }

    public void setExpirytime(LocalDateTime expirytime) {
        this.expirytime = expirytime;
    }

    public String getAccountnum() {
        return this.accountnum;
    }

    public void setAccountnum(String accountnum) {
        this.accountnum = accountnum;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Accesstoken (");

        sb.append(accesstoken);
        sb.append(", ").append(expirytime);
        sb.append(", ").append(accountnum);

        sb.append(")");
        return sb.toString();
    }
}
