/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authorization implements Serializable {

    private static final long serialVersionUID = -1855588286;

    private String  name;
    private Integer type;
    private String  accountnum;
    private String  password;
    private String  token;

    public Authorization() {}

    public Authorization(Authorization value) {
        this.name = value.name;
        this.type = value.type;
        this.accountnum = value.accountnum;
        this.password = value.password;
        this.token = value.token;
    }

    public Authorization(
        String  name,
        Integer type,
        String  accountnum,
        String  password,
        String  token
    ) {
        this.name = name;
        this.type = type;
        this.accountnum = accountnum;
        this.password = password;
        this.token = token;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Integer getType() {
        return this.type;
    }

    public void setType(Integer type) {
        this.type = type;
    }

    public String getAccountnum() {
        return this.accountnum;
    }

    public void setAccountnum(String accountnum) {
        this.accountnum = accountnum;
    }

    public String getPassword() {
        return this.password;
    }

    public void setPassword(String password) {
        this.password = password;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Authorization (");

        sb.append(name);
        sb.append(", ").append(type);
        sb.append(", ").append(accountnum);
        sb.append(", ").append(password);
        sb.append(", ").append(token);

        sb.append(")");
        return sb.toString();
    }
}
