/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Company implements Serializable {

    private static final long serialVersionUID = -933646911;

    private Integer       id;
    private String        name;
    private String        phoneNumber;
    private String        email;
    private String        token;
    private Integer       credit;
    private String        status;
    private String        address;
    private String        businessLicenseCode;
    private LocalDateTime startDate;
    private LocalDateTime endDate;
    private String        businessRegistrationCode;
    private String        industry;
    private String        registedCapital;
    private String        operationType;

    public Company() {}

    public Company(Company value) {
        this.id = value.id;
        this.name = value.name;
        this.phoneNumber = value.phoneNumber;
        this.email = value.email;
        this.token = value.token;
        this.credit = value.credit;
        this.status = value.status;
        this.address = value.address;
        this.businessLicenseCode = value.businessLicenseCode;
        this.startDate = value.startDate;
        this.endDate = value.endDate;
        this.businessRegistrationCode = value.businessRegistrationCode;
        this.industry = value.industry;
        this.registedCapital = value.registedCapital;
        this.operationType = value.operationType;
    }

    public Company(
        Integer       id,
        String        name,
        String        phoneNumber,
        String        email,
        String        token,
        Integer       credit,
        String        status,
        String        address,
        String        businessLicenseCode,
        LocalDateTime startDate,
        LocalDateTime endDate,
        String        businessRegistrationCode,
        String        industry,
        String        registedCapital,
        String        operationType
    ) {
        this.id = id;
        this.name = name;
        this.phoneNumber = phoneNumber;
        this.email = email;
        this.token = token;
        this.credit = credit;
        this.status = status;
        this.address = address;
        this.businessLicenseCode = businessLicenseCode;
        this.startDate = startDate;
        this.endDate = endDate;
        this.businessRegistrationCode = businessRegistrationCode;
        this.industry = industry;
        this.registedCapital = registedCapital;
        this.operationType = operationType;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getPhoneNumber() {
        return this.phoneNumber;
    }

    public void setPhoneNumber(String phoneNumber) {
        this.phoneNumber = phoneNumber;
    }

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getToken() {
        return this.token;
    }

    public void setToken(String token) {
        this.token = token;
    }

    public Integer getCredit() {
        return this.credit;
    }

    public void setCredit(Integer credit) {
        this.credit = credit;
    }

    public String getStatus() {
        return this.status;
    }

    public void setStatus(String status) {
        this.status = status;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getBusinessLicenseCode() {
        return this.businessLicenseCode;
    }

    public void setBusinessLicenseCode(String businessLicenseCode) {
        this.businessLicenseCode = businessLicenseCode;
    }

    public LocalDateTime getStartDate() {
        return this.startDate;
    }

    public void setStartDate(LocalDateTime startDate) {
        this.startDate = startDate;
    }

    public LocalDateTime getEndDate() {
        return this.endDate;
    }

    public void setEndDate(LocalDateTime endDate) {
        this.endDate = endDate;
    }

    public String getBusinessRegistrationCode() {
        return this.businessRegistrationCode;
    }

    public void setBusinessRegistrationCode(String businessRegistrationCode) {
        this.businessRegistrationCode = businessRegistrationCode;
    }

    public String getIndustry() {
        return this.industry;
    }

    public void setIndustry(String industry) {
        this.industry = industry;
    }

    public String getRegistedCapital() {
        return this.registedCapital;
    }

    public void setRegistedCapital(String registedCapital) {
        this.registedCapital = registedCapital;
    }

    public String getOperationType() {
        return this.operationType;
    }

    public void setOperationType(String operationType) {
        this.operationType = operationType;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Company (");

        sb.append(id);
        sb.append(", ").append(name);
        sb.append(", ").append(phoneNumber);
        sb.append(", ").append(email);
        sb.append(", ").append(token);
        sb.append(", ").append(credit);
        sb.append(", ").append(status);
        sb.append(", ").append(address);
        sb.append(", ").append(businessLicenseCode);
        sb.append(", ").append(startDate);
        sb.append(", ").append(endDate);
        sb.append(", ").append(businessRegistrationCode);
        sb.append(", ").append(industry);
        sb.append(", ").append(registedCapital);
        sb.append(", ").append(operationType);

        sb.append(")");
        return sb.toString();
    }
}
