/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Creditupdatetask implements Serializable {

    private static final long serialVersionUID = 1266305575;

    private Integer id;
    private String  accountnum;
    private Integer previouscredit;
    private Integer delta;
    private String  state;
    private String  timestamp;
    private String  reason;

    public Creditupdatetask() {}

    public Creditupdatetask(Creditupdatetask value) {
        this.id = value.id;
        this.accountnum = value.accountnum;
        this.previouscredit = value.previouscredit;
        this.delta = value.delta;
        this.state = value.state;
        this.timestamp = value.timestamp;
        this.reason = value.reason;
    }

    public Creditupdatetask(
        Integer id,
        String  accountnum,
        Integer previouscredit,
        Integer delta,
        String  state,
        String  timestamp,
        String  reason
    ) {
        this.id = id;
        this.accountnum = accountnum;
        this.previouscredit = previouscredit;
        this.delta = delta;
        this.state = state;
        this.timestamp = timestamp;
        this.reason = reason;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getAccountnum() {
        return this.accountnum;
    }

    public void setAccountnum(String accountnum) {
        this.accountnum = accountnum;
    }

    public Integer getPreviouscredit() {
        return this.previouscredit;
    }

    public void setPreviouscredit(Integer previouscredit) {
        this.previouscredit = previouscredit;
    }

    public Integer getDelta() {
        return this.delta;
    }

    public void setDelta(Integer delta) {
        this.delta = delta;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getTimestamp() {
        return this.timestamp;
    }

    public void setTimestamp(String timestamp) {
        this.timestamp = timestamp;
    }

    public String getReason() {
        return this.reason;
    }

    public void setReason(String reason) {
        this.reason = reason;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Creditupdatetask (");

        sb.append(id);
        sb.append(", ").append(accountnum);
        sb.append(", ").append(previouscredit);
        sb.append(", ").append(delta);
        sb.append(", ").append(state);
        sb.append(", ").append(timestamp);
        sb.append(", ").append(reason);

        sb.append(")");
        return sb.toString();
    }
}
