/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Guaranty implements Serializable {

    private static final long serialVersionUID = -1149594914;

    private Integer id;
    private String  companyId;
    private String  state;
    private String  rightScope;
    private String  ownerName;
    private String  reportId;
    private String  type;
    private Integer evaluateValue;
    private String  name;
    private String  producer;
    private String  model;
    private Integer usedDays;
    private String  address;
    private String  area;
    private String  zip;
    private Byte    lock;

    public Guaranty() {}

    public Guaranty(Guaranty value) {
        this.id = value.id;
        this.companyId = value.companyId;
        this.state = value.state;
        this.rightScope = value.rightScope;
        this.ownerName = value.ownerName;
        this.reportId = value.reportId;
        this.type = value.type;
        this.evaluateValue = value.evaluateValue;
        this.name = value.name;
        this.producer = value.producer;
        this.model = value.model;
        this.usedDays = value.usedDays;
        this.address = value.address;
        this.area = value.area;
        this.zip = value.zip;
        this.lock = value.lock;
    }

    public Guaranty(
        Integer id,
        String  companyId,
        String  state,
        String  rightScope,
        String  ownerName,
        String  reportId,
        String  type,
        Integer evaluateValue,
        String  name,
        String  producer,
        String  model,
        Integer usedDays,
        String  address,
        String  area,
        String  zip,
        Byte    lock
    ) {
        this.id = id;
        this.companyId = companyId;
        this.state = state;
        this.rightScope = rightScope;
        this.ownerName = ownerName;
        this.reportId = reportId;
        this.type = type;
        this.evaluateValue = evaluateValue;
        this.name = name;
        this.producer = producer;
        this.model = model;
        this.usedDays = usedDays;
        this.address = address;
        this.area = area;
        this.zip = zip;
        this.lock = lock;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public String getState() {
        return this.state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getRightScope() {
        return this.rightScope;
    }

    public void setRightScope(String rightScope) {
        this.rightScope = rightScope;
    }

    public String getOwnerName() {
        return this.ownerName;
    }

    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName;
    }

    public String getReportId() {
        return this.reportId;
    }

    public void setReportId(String reportId) {
        this.reportId = reportId;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    public Integer getEvaluateValue() {
        return this.evaluateValue;
    }

    public void setEvaluateValue(Integer evaluateValue) {
        this.evaluateValue = evaluateValue;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getProducer() {
        return this.producer;
    }

    public void setProducer(String producer) {
        this.producer = producer;
    }

    public String getModel() {
        return this.model;
    }

    public void setModel(String model) {
        this.model = model;
    }

    public Integer getUsedDays() {
        return this.usedDays;
    }

    public void setUsedDays(Integer usedDays) {
        this.usedDays = usedDays;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    public String getArea() {
        return this.area;
    }

    public void setArea(String area) {
        this.area = area;
    }

    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public Byte getLock() {
        return this.lock;
    }

    public void setLock(Byte lock) {
        this.lock = lock;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Guaranty (");

        sb.append(id);
        sb.append(", ").append(companyId);
        sb.append(", ").append(state);
        sb.append(", ").append(rightScope);
        sb.append(", ").append(ownerName);
        sb.append(", ").append(reportId);
        sb.append(", ").append(type);
        sb.append(", ").append(evaluateValue);
        sb.append(", ").append(name);
        sb.append(", ").append(producer);
        sb.append(", ").append(model);
        sb.append(", ").append(usedDays);
        sb.append(", ").append(address);
        sb.append(", ").append(area);
        sb.append(", ").append(zip);
        sb.append(", ").append(lock);

        sb.append(")");
        return sb.toString();
    }
}
