/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class House implements Serializable {

    private static final long serialVersionUID = 781850537;

    private String  addr;
    private String  zip;
    private String  housingcertificatedid;
    private Integer guarantyid;

    public House() {}

    public House(House value) {
        this.addr = value.addr;
        this.zip = value.zip;
        this.housingcertificatedid = value.housingcertificatedid;
        this.guarantyid = value.guarantyid;
    }

    public House(
        String  addr,
        String  zip,
        String  housingcertificatedid,
        Integer guarantyid
    ) {
        this.addr = addr;
        this.zip = zip;
        this.housingcertificatedid = housingcertificatedid;
        this.guarantyid = guarantyid;
    }

    public String getAddr() {
        return this.addr;
    }

    public void setAddr(String addr) {
        this.addr = addr;
    }

    public String getZip() {
        return this.zip;
    }

    public void setZip(String zip) {
        this.zip = zip;
    }

    public String getHousingcertificatedid() {
        return this.housingcertificatedid;
    }

    public void setHousingcertificatedid(String housingcertificatedid) {
        this.housingcertificatedid = housingcertificatedid;
    }

    public Integer getGuarantyid() {
        return this.guarantyid;
    }

    public void setGuarantyid(Integer guarantyid) {
        this.guarantyid = guarantyid;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("House (");

        sb.append(addr);
        sb.append(", ").append(zip);
        sb.append(", ").append(housingcertificatedid);
        sb.append(", ").append(guarantyid);

        sb.append(")");
        return sb.toString();
    }
}
