/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Report implements Serializable {

    private static final long serialVersionUID = 253970053;

    private String        accountnum;
    private Integer       reportid;
    private LocalDateTime date;
    private String        duration;
    private String        type;

    public Report() {}

    public Report(Report value) {
        this.accountnum = value.accountnum;
        this.reportid = value.reportid;
        this.date = value.date;
        this.duration = value.duration;
        this.type = value.type;
    }

    public Report(
        String        accountnum,
        Integer       reportid,
        LocalDateTime date,
        String        duration,
        String        type
    ) {
        this.accountnum = accountnum;
        this.reportid = reportid;
        this.date = date;
        this.duration = duration;
        this.type = type;
    }

    public String getAccountnum() {
        return this.accountnum;
    }

    public void setAccountnum(String accountnum) {
        this.accountnum = accountnum;
    }

    public Integer getReportid() {
        return this.reportid;
    }

    public void setReportid(Integer reportid) {
        this.reportid = reportid;
    }

    public LocalDateTime getDate() {
        return this.date;
    }

    public void setDate(LocalDateTime date) {
        this.date = date;
    }

    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public String getType() {
        return this.type;
    }

    public void setType(String type) {
        this.type = type;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Report (");

        sb.append(accountnum);
        sb.append(", ").append(reportid);
        sb.append(", ").append(date);
        sb.append(", ").append(duration);
        sb.append(", ").append(type);

        sb.append(")");
        return sb.toString();
    }
}
