/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Report implements Serializable {

    private static final long serialVersionUID = -150785864;

    private Integer       id;
    private String        companyId;
    private LocalDateTime createDate;
    private String        duration;

    public Report() {}

    public Report(Report value) {
        this.id = value.id;
        this.companyId = value.companyId;
        this.createDate = value.createDate;
        this.duration = value.duration;
    }

    public Report(
        Integer       id,
        String        companyId,
        LocalDateTime createDate,
        String        duration
    ) {
        this.id = id;
        this.companyId = companyId;
        this.createDate = createDate;
        this.duration = duration;
    }

    public Integer getId() {
        return this.id;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public String getCompanyId() {
        return this.companyId;
    }

    public void setCompanyId(String companyId) {
        this.companyId = companyId;
    }

    public LocalDateTime getCreateDate() {
        return this.createDate;
    }

    public void setCreateDate(LocalDateTime createDate) {
        this.createDate = createDate;
    }

    public String getDuration() {
        return this.duration;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("Report (");

        sb.append(id);
        sb.append(", ").append(companyId);
        sb.append(", ").append(createDate);
        sb.append(", ").append(duration);

        sb.append(")");
        return sb.toString();
    }
}
