/*
 * This file is generated by jOOQ.
*/
package com.bcgenerator.tables.pojos;


import java.io.Serializable;
import java.time.LocalDateTime;

import javax.annotation.Generated;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditChain implements Serializable {

    private static final long serialVersionUID = 951589723;

    private String        thisHash;
    private LocalDateTime timeStamp;
    private String        previousHash;
    private Long          length;
    private Byte          isMain;
    private String        nearestMainHash;
    private String        address;

    public CreditChain() {}

    public CreditChain(CreditChain value) {
        this.thisHash = value.thisHash;
        this.timeStamp = value.timeStamp;
        this.previousHash = value.previousHash;
        this.length = value.length;
        this.isMain = value.isMain;
        this.nearestMainHash = value.nearestMainHash;
        this.address = value.address;
    }

    public CreditChain(
        String        thisHash,
        LocalDateTime timeStamp,
        String        previousHash,
        Long          length,
        Byte          isMain,
        String        nearestMainHash,
        String        address
    ) {
        this.thisHash = thisHash;
        this.timeStamp = timeStamp;
        this.previousHash = previousHash;
        this.length = length;
        this.isMain = isMain;
        this.nearestMainHash = nearestMainHash;
        this.address = address;
    }

    public String getThisHash() {
        return this.thisHash;
    }

    public void setThisHash(String thisHash) {
        this.thisHash = thisHash;
    }

    public LocalDateTime getTimeStamp() {
        return this.timeStamp;
    }

    public void setTimeStamp(LocalDateTime timeStamp) {
        this.timeStamp = timeStamp;
    }

    public String getPreviousHash() {
        return this.previousHash;
    }

    public void setPreviousHash(String previousHash) {
        this.previousHash = previousHash;
    }

    public Long getLength() {
        return this.length;
    }

    public void setLength(Long length) {
        this.length = length;
    }

    public Byte getIsMain() {
        return this.isMain;
    }

    public void setIsMain(Byte isMain) {
        this.isMain = isMain;
    }

    public String getNearestMainHash() {
        return this.nearestMainHash;
    }

    public void setNearestMainHash(String nearestMainHash) {
        this.nearestMainHash = nearestMainHash;
    }

    public String getAddress() {
        return this.address;
    }

    public void setAddress(String address) {
        this.address = address;
    }

    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder("CreditChain (");

        sb.append(thisHash);
        sb.append(", ").append(timeStamp);
        sb.append(", ").append(previousHash);
        sb.append(", ").append(length);
        sb.append(", ").append(isMain);
        sb.append(", ").append(nearestMainHash);
        sb.append(", ").append(address);

        sb.append(")");
        return sb.toString();
    }
}
