/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.generator.tables.Accesstoken;
import com.generator.tables.records.AccesstokenRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccesstokenDao extends DAOImpl<AccesstokenRecord, com.generator.tables.pojos.Accesstoken, Integer> {

    /**
     * Create a new AccesstokenDao without any configuration
     */
    public AccesstokenDao() {
        super(Accesstoken.ACCESSTOKEN, com.generator.tables.pojos.Accesstoken.class);
    }

    /**
     * Create a new AccesstokenDao with an attached configuration
     */
    public AccesstokenDao(Configuration configuration) {
        super(Accesstoken.ACCESSTOKEN, com.generator.tables.pojos.Accesstoken.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.generator.tables.pojos.Accesstoken object) {
        return object.getId();
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.generator.tables.pojos.Accesstoken> fetchById(Integer... values) {
        return fetch(Accesstoken.ACCESSTOKEN.ID, values);
    }

    /**
     * Fetch a unique record that has <code>id = value</code>
     */
    public com.generator.tables.pojos.Accesstoken fetchOneById(Integer value) {
        return fetchOne(Accesstoken.ACCESSTOKEN.ID, value);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.generator.tables.pojos.Accesstoken> fetchByValue(String... values) {
        return fetch(Accesstoken.ACCESSTOKEN.VALUE, values);
    }

    /**
     * Fetch records that have <code>expire_time IN (values)</code>
     */
    public List<com.generator.tables.pojos.Accesstoken> fetchByExpireTime(String... values) {
        return fetch(Accesstoken.ACCESSTOKEN.EXPIRE_TIME, values);
    }

    /**
     * Fetch records that have <code>company_id IN (values)</code>
     */
    public List<com.generator.tables.pojos.Accesstoken> fetchByCompanyId(String... values) {
        return fetch(Accesstoken.ACCESSTOKEN.COMPANY_ID, values);
    }
}
