/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.generator.tables.GuarantyChain;
import com.generator.tables.records.GuarantyChainRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuarantyChainDao extends DAOImpl<GuarantyChainRecord, com.generator.tables.pojos.GuarantyChain, String> {

    /**
     * Create a new GuarantyChainDao without any configuration
     */
    public GuarantyChainDao() {
        super(GuarantyChain.GUARANTY_CHAIN, com.generator.tables.pojos.GuarantyChain.class);
    }

    /**
     * Create a new GuarantyChainDao with an attached configuration
     */
    public GuarantyChainDao(Configuration configuration) {
        super(GuarantyChain.GUARANTY_CHAIN, com.generator.tables.pojos.GuarantyChain.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.generator.tables.pojos.GuarantyChain object) {
        return object.getThisHash();
    }

    /**
     * Fetch records that have <code>this_hash IN (values)</code>
     */
    public List<com.generator.tables.pojos.GuarantyChain> fetchByThisHash(String... values) {
        return fetch(GuarantyChain.GUARANTY_CHAIN.THIS_HASH, values);
    }

    /**
     * Fetch a unique record that has <code>this_hash = value</code>
     */
    public com.generator.tables.pojos.GuarantyChain fetchOneByThisHash(String value) {
        return fetchOne(GuarantyChain.GUARANTY_CHAIN.THIS_HASH, value);
    }

    /**
     * Fetch records that have <code>time_stamp IN (values)</code>
     */
    public List<com.generator.tables.pojos.GuarantyChain> fetchByTimeStamp(LocalDateTime... values) {
        return fetch(GuarantyChain.GUARANTY_CHAIN.TIME_STAMP, values);
    }

    /**
     * Fetch records that have <code>previous_hash IN (values)</code>
     */
    public List<com.generator.tables.pojos.GuarantyChain> fetchByPreviousHash(String... values) {
        return fetch(GuarantyChain.GUARANTY_CHAIN.PREVIOUS_HASH, values);
    }

    /**
     * Fetch records that have <code>length IN (values)</code>
     */
    public List<com.generator.tables.pojos.GuarantyChain> fetchByLength(Long... values) {
        return fetch(GuarantyChain.GUARANTY_CHAIN.LENGTH, values);
    }

    /**
     * Fetch records that have <code>is_main IN (values)</code>
     */
    public List<com.generator.tables.pojos.GuarantyChain> fetchByIsMain(Byte... values) {
        return fetch(GuarantyChain.GUARANTY_CHAIN.IS_MAIN, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.generator.tables.pojos.GuarantyChain> fetchByAddress(String... values) {
        return fetch(GuarantyChain.GUARANTY_CHAIN.ADDRESS, values);
    }
}
