/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.generator.tables.Machine;
import com.generator.tables.records.MachineRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class MachineDao extends DAOImpl<MachineRecord, com.generator.tables.pojos.Machine, Integer> {

    /**
     * Create a new MachineDao without any configuration
     */
    public MachineDao() {
        super(Machine.MACHINE, com.generator.tables.pojos.Machine.class);
    }

    /**
     * Create a new MachineDao with an attached configuration
     */
    public MachineDao(Configuration configuration) {
        super(Machine.MACHINE, com.generator.tables.pojos.Machine.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.generator.tables.pojos.Machine object) {
        return object.getGuarantyid();
    }

    /**
     * Fetch records that have <code>UsedDays IN (values)</code>
     */
    public List<com.generator.tables.pojos.Machine> fetchByUseddays(Integer... values) {
        return fetch(Machine.MACHINE.USEDDAYS, values);
    }

    /**
     * Fetch records that have <code>Producer IN (values)</code>
     */
    public List<com.generator.tables.pojos.Machine> fetchByProducer(String... values) {
        return fetch(Machine.MACHINE.PRODUCER, values);
    }

    /**
     * Fetch records that have <code>Model IN (values)</code>
     */
    public List<com.generator.tables.pojos.Machine> fetchByModel(String... values) {
        return fetch(Machine.MACHINE.MODEL, values);
    }

    /**
     * Fetch records that have <code>GuarantyId IN (values)</code>
     */
    public List<com.generator.tables.pojos.Machine> fetchByGuarantyid(Integer... values) {
        return fetch(Machine.MACHINE.GUARANTYID, values);
    }

    /**
     * Fetch a unique record that has <code>GuarantyId = value</code>
     */
    public com.generator.tables.pojos.Machine fetchOneByGuarantyid(Integer value) {
        return fetchOne(Machine.MACHINE.GUARANTYID, value);
    }
}
