/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.generator.tables.Report;
import com.generator.tables.records.ReportRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ReportDao extends DAOImpl<ReportRecord, com.generator.tables.pojos.Report, Integer> {

    /**
     * Create a new ReportDao without any configuration
     */
    public ReportDao() {
        super(Report.REPORT, com.generator.tables.pojos.Report.class);
    }

    /**
     * Create a new ReportDao with an attached configuration
     */
    public ReportDao(Configuration configuration) {
        super(Report.REPORT, com.generator.tables.pojos.Report.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Integer getId(com.generator.tables.pojos.Report object) {
        return object.getReportid();
    }

    /**
     * Fetch records that have <code>AccountNum IN (values)</code>
     */
    public List<com.generator.tables.pojos.Report> fetchByAccountnum(String... values) {
        return fetch(Report.REPORT.ACCOUNTNUM, values);
    }

    /**
     * Fetch records that have <code>ReportId IN (values)</code>
     */
    public List<com.generator.tables.pojos.Report> fetchByReportid(Integer... values) {
        return fetch(Report.REPORT.REPORTID, values);
    }

    /**
     * Fetch a unique record that has <code>ReportId = value</code>
     */
    public com.generator.tables.pojos.Report fetchOneByReportid(Integer value) {
        return fetchOne(Report.REPORT.REPORTID, value);
    }

    /**
     * Fetch records that have <code>Date IN (values)</code>
     */
    public List<com.generator.tables.pojos.Report> fetchByDate(LocalDateTime... values) {
        return fetch(Report.REPORT.DATE, values);
    }

    /**
     * Fetch records that have <code>Duration IN (values)</code>
     */
    public List<com.generator.tables.pojos.Report> fetchByDuration(String... values) {
        return fetch(Report.REPORT.DURATION, values);
    }
}
