/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.daos;


import com.generator.tables.Securitiesinformation;
import com.generator.tables.records.SecuritiesinformationRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecuritiesinformationDao extends DAOImpl<SecuritiesinformationRecord, com.generator.tables.pojos.Securitiesinformation, String> {

    /**
     * Create a new SecuritiesinformationDao without any configuration
     */
    public SecuritiesinformationDao() {
        super(Securitiesinformation.SECURITIESINFORMATION, com.generator.tables.pojos.Securitiesinformation.class);
    }

    /**
     * Create a new SecuritiesinformationDao with an attached configuration
     */
    public SecuritiesinformationDao(Configuration configuration) {
        super(Securitiesinformation.SECURITIESINFORMATION, com.generator.tables.pojos.Securitiesinformation.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.generator.tables.pojos.Securitiesinformation object) {
        return object.getAccountnum();
    }

    /**
     * Fetch records that have <code>AccountNum IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByAccountnum(String... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.ACCOUNTNUM, values);
    }

    /**
     * Fetch a unique record that has <code>AccountNum = value</code>
     */
    public com.generator.tables.pojos.Securitiesinformation fetchOneByAccountnum(String value) {
        return fetchOne(Securitiesinformation.SECURITIESINFORMATION.ACCOUNTNUM, value);
    }

    /**
     * Fetch records that have <code>StockCode IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByStockcode(String... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.STOCKCODE, values);
    }

    /**
     * Fetch records that have <code>ListedApproval IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByListedapproval(String... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.LISTEDAPPROVAL, values);
    }

    /**
     * Fetch records that have <code>StockAbbr IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByStockabbr(String... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.STOCKABBR, values);
    }

    /**
     * Fetch records that have <code>IssuePrice IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByIssueprice(Long... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.ISSUEPRICE, values);
    }

    /**
     * Fetch records that have <code>StockType IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByStocktype(Integer... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.STOCKTYPE, values);
    }

    /**
     * Fetch records that have <code>LaunchDate IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByLaunchdate(LocalDateTime... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.LAUNCHDATE, values);
    }

    /**
     * Fetch records that have <code>Circulation IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByCirculation(Long... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.CIRCULATION, values);
    }

    /**
     * Fetch records that have <code>IsValid IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByIsvalid(Byte... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.ISVALID, values);
    }

    /**
     * Fetch records that have <code>Remark IN (values)</code>
     */
    public List<com.generator.tables.pojos.Securitiesinformation> fetchByRemark(String... values) {
        return fetch(Securitiesinformation.SECURITIESINFORMATION.REMARK, values);
    }
}
