/*
 * This file is generated by jOOQ.
*/
package com.bcgenerator.tables.records;


import com.bcgenerator.tables.GuarantyData;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record2;
import org.jooq.Record5;
import org.jooq.Row5;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuarantyDataRecord extends UpdatableRecordImpl<GuarantyDataRecord> implements Record5<String, String, String, String, String> {

    private static final long serialVersionUID = 1038315957;

    /**
     * Setter for <code>blockchain.guaranty_data.block_hash</code>.
     */
    public void setBlockHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>blockchain.guaranty_data.block_hash</code>.
     */
    public String getBlockHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>blockchain.guaranty_data.id</code>.
     */
    public void setId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>blockchain.guaranty_data.id</code>.
     */
    public String getId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>blockchain.guaranty_data.variation</code>.
     */
    public void setVariation(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>blockchain.guaranty_data.variation</code>.
     */
    public String getVariation() {
        return (String) get(2);
    }

    /**
     * Setter for <code>blockchain.guaranty_data.value</code>.
     */
    public void setValue(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>blockchain.guaranty_data.value</code>.
     */
    public String getValue() {
        return (String) get(3);
    }

    /**
     * Setter for <code>blockchain.guaranty_data.remarks</code>.
     */
    public void setRemarks(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>blockchain.guaranty_data.remarks</code>.
     */
    public String getRemarks() {
        return (String) get(4);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record2<String, String> key() {
        return (Record2) super.key();
    }

    // -------------------------------------------------------------------------
    // Record5 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> fieldsRow() {
        return (Row5) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row5<String, String, String, String, String> valuesRow() {
        return (Row5) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return GuarantyData.GUARANTY_DATA.BLOCK_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return GuarantyData.GUARANTY_DATA.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return GuarantyData.GUARANTY_DATA.VARIATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return GuarantyData.GUARANTY_DATA.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return GuarantyData.GUARANTY_DATA.REMARKS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getVariation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getBlockHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getVariation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getRemarks();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyDataRecord value1(String value) {
        setBlockHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyDataRecord value2(String value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyDataRecord value3(String value) {
        setVariation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyDataRecord value4(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyDataRecord value5(String value) {
        setRemarks(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyDataRecord values(String value1, String value2, String value3, String value4, String value5) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuarantyDataRecord
     */
    public GuarantyDataRecord() {
        super(GuarantyData.GUARANTY_DATA);
    }

    /**
     * Create a detached, initialised GuarantyDataRecord
     */
    public GuarantyDataRecord(String blockHash, String id, String variation, String value, String remarks) {
        super(GuarantyData.GUARANTY_DATA);

        set(0, blockHash);
        set(1, id);
        set(2, variation);
        set(3, value);
        set(4, remarks);
    }
}
