/*
 * This file is generated by jOOQ.
*/
package com.bcgenerator.tables.daos;


import com.bcgenerator.tables.CreditChain;
import com.bcgenerator.tables.records.CreditChainRecord;

import java.time.LocalDateTime;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditChainDao extends DAOImpl<CreditChainRecord, com.bcgenerator.tables.pojos.CreditChain, String> {

    /**
     * Create a new CreditChainDao without any configuration
     */
    public CreditChainDao() {
        super(CreditChain.CREDIT_CHAIN, com.bcgenerator.tables.pojos.CreditChain.class);
    }

    /**
     * Create a new CreditChainDao with an attached configuration
     */
    public CreditChainDao(Configuration configuration) {
        super(CreditChain.CREDIT_CHAIN, com.bcgenerator.tables.pojos.CreditChain.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected String getId(com.bcgenerator.tables.pojos.CreditChain object) {
        return object.getThisHash();
    }

    /**
     * Fetch records that have <code>this_hash IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.CreditChain> fetchByThisHash(String... values) {
        return fetch(CreditChain.CREDIT_CHAIN.THIS_HASH, values);
    }

    /**
     * Fetch a unique record that has <code>this_hash = value</code>
     */
    public com.bcgenerator.tables.pojos.CreditChain fetchOneByThisHash(String value) {
        return fetchOne(CreditChain.CREDIT_CHAIN.THIS_HASH, value);
    }

    /**
     * Fetch records that have <code>time_stamp IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.CreditChain> fetchByTimeStamp(LocalDateTime... values) {
        return fetch(CreditChain.CREDIT_CHAIN.TIME_STAMP, values);
    }

    /**
     * Fetch records that have <code>previous_hash IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.CreditChain> fetchByPreviousHash(String... values) {
        return fetch(CreditChain.CREDIT_CHAIN.PREVIOUS_HASH, values);
    }

    /**
     * Fetch records that have <code>length IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.CreditChain> fetchByLength(Long... values) {
        return fetch(CreditChain.CREDIT_CHAIN.LENGTH, values);
    }

    /**
     * Fetch records that have <code>is_main IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.CreditChain> fetchByIsMain(Byte... values) {
        return fetch(CreditChain.CREDIT_CHAIN.IS_MAIN, values);
    }

    /**
     * Fetch records that have <code>nearest_main_hash IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.CreditChain> fetchByNearestMainHash(String... values) {
        return fetch(CreditChain.CREDIT_CHAIN.NEAREST_MAIN_HASH, values);
    }

    /**
     * Fetch records that have <code>address IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.CreditChain> fetchByAddress(String... values) {
        return fetch(CreditChain.CREDIT_CHAIN.ADDRESS, values);
    }
}
