/*
 * This file is generated by jOOQ.
*/
package com.bcgenerator.tables.daos;


import com.bcgenerator.tables.GuarantyData;
import com.bcgenerator.tables.records.GuarantyDataRecord;

import java.util.List;

import javax.annotation.Generated;

import org.jooq.Configuration;
import org.jooq.Record2;
import org.jooq.impl.DAOImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuarantyDataDao extends DAOImpl<GuarantyDataRecord, com.bcgenerator.tables.pojos.GuarantyData, Record2<String, String>> {

    /**
     * Create a new GuarantyDataDao without any configuration
     */
    public GuarantyDataDao() {
        super(GuarantyData.GUARANTY_DATA, com.bcgenerator.tables.pojos.GuarantyData.class);
    }

    /**
     * Create a new GuarantyDataDao with an attached configuration
     */
    public GuarantyDataDao(Configuration configuration) {
        super(GuarantyData.GUARANTY_DATA, com.bcgenerator.tables.pojos.GuarantyData.class, configuration);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    protected Record2<String, String> getId(com.bcgenerator.tables.pojos.GuarantyData object) {
        return compositeKeyRecord(object.getBlockHash(), object.getId());
    }

    /**
     * Fetch records that have <code>block_hash IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.GuarantyData> fetchByBlockHash(String... values) {
        return fetch(GuarantyData.GUARANTY_DATA.BLOCK_HASH, values);
    }

    /**
     * Fetch records that have <code>id IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.GuarantyData> fetchById(String... values) {
        return fetch(GuarantyData.GUARANTY_DATA.ID, values);
    }

    /**
     * Fetch records that have <code>variation IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.GuarantyData> fetchByVariation(String... values) {
        return fetch(GuarantyData.GUARANTY_DATA.VARIATION, values);
    }

    /**
     * Fetch records that have <code>value IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.GuarantyData> fetchByValue(String... values) {
        return fetch(GuarantyData.GUARANTY_DATA.VALUE, values);
    }

    /**
     * Fetch records that have <code>remarks IN (values)</code>
     */
    public List<com.bcgenerator.tables.pojos.GuarantyData> fetchByRemarks(String... values) {
        return fetch(GuarantyData.GUARANTY_DATA.REMARKS, values);
    }
}
