/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.generator.Bcinvest;
import com.generator.Indexes;
import com.generator.Keys;
import com.generator.tables.records.AccesstokenRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Accesstoken extends TableImpl<AccesstokenRecord> {

    private static final long serialVersionUID = 64034407;

    /**
     * The reference instance of <code>bcinvest.AccessToken</code>
     */
    public static final Accesstoken ACCESSTOKEN = new Accesstoken();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AccesstokenRecord> getRecordType() {
        return AccesstokenRecord.class;
    }

    /**
     * The column <code>bcinvest.AccessToken.id</code>.
     */
    public final TableField<AccesstokenRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>bcinvest.AccessToken.value</code>.
     */
    public final TableField<AccesstokenRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>bcinvest.AccessToken.expire_time</code>.
     */
    public final TableField<AccesstokenRecord, String> EXPIRE_TIME = createField("expire_time", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>bcinvest.AccessToken.company_id</code>.
     */
    public final TableField<AccesstokenRecord, String> COMPANY_ID = createField("company_id", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * Create a <code>bcinvest.AccessToken</code> table reference
     */
    public Accesstoken() {
        this(DSL.name("AccessToken"), null);
    }

    /**
     * Create an aliased <code>bcinvest.AccessToken</code> table reference
     */
    public Accesstoken(String alias) {
        this(DSL.name(alias), ACCESSTOKEN);
    }

    /**
     * Create an aliased <code>bcinvest.AccessToken</code> table reference
     */
    public Accesstoken(Name alias) {
        this(alias, ACCESSTOKEN);
    }

    private Accesstoken(Name alias, Table<AccesstokenRecord> aliased) {
        this(alias, aliased, null);
    }

    private Accesstoken(Name alias, Table<AccesstokenRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bcinvest.BCINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.ACCESSTOKEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AccesstokenRecord, Integer> getIdentity() {
        return Keys.IDENTITY_ACCESSTOKEN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AccesstokenRecord> getPrimaryKey() {
        return Keys.KEY_ACCESSTOKEN_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AccesstokenRecord>> getKeys() {
        return Arrays.<UniqueKey<AccesstokenRecord>>asList(Keys.KEY_ACCESSTOKEN_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Accesstoken as(String alias) {
        return new Accesstoken(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Accesstoken as(Name alias) {
        return new Accesstoken(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Accesstoken rename(String name) {
        return new Accesstoken(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Accesstoken rename(Name name) {
        return new Accesstoken(name, null);
    }
}
