/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.generator.Bcinvest;
import com.generator.Indexes;
import com.generator.Keys;
import com.generator.tables.records.AuthorityRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authority extends TableImpl<AuthorityRecord> {

    private static final long serialVersionUID = -474403644;

    /**
     * The reference instance of <code>bcinvest.Authority</code>
     */
    public static final Authority AUTHORITY = new Authority();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorityRecord> getRecordType() {
        return AuthorityRecord.class;
    }

    /**
     * The column <code>bcinvest.Authority.id</code>.
     */
    public final TableField<AuthorityRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>bcinvest.Authority.token</code>.
     */
    public final TableField<AuthorityRecord, String> TOKEN = createField("token", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>bcinvest.Authority.username</code>.
     */
    public final TableField<AuthorityRecord, String> USERNAME = createField("username", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * The column <code>bcinvest.Authority.password</code>.
     */
    public final TableField<AuthorityRecord, String> PASSWORD = createField("password", org.jooq.impl.SQLDataType.VARCHAR(45), this, "");

    /**
     * Create a <code>bcinvest.Authority</code> table reference
     */
    public Authority() {
        this(DSL.name("Authority"), null);
    }

    /**
     * Create an aliased <code>bcinvest.Authority</code> table reference
     */
    public Authority(String alias) {
        this(DSL.name(alias), AUTHORITY);
    }

    /**
     * Create an aliased <code>bcinvest.Authority</code> table reference
     */
    public Authority(Name alias) {
        this(alias, AUTHORITY);
    }

    private Authority(Name alias, Table<AuthorityRecord> aliased) {
        this(alias, aliased, null);
    }

    private Authority(Name alias, Table<AuthorityRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bcinvest.BCINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTHORITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<AuthorityRecord, Integer> getIdentity() {
        return Keys.IDENTITY_AUTHORITY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthorityRecord> getPrimaryKey() {
        return Keys.KEY_AUTHORITY_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthorityRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorityRecord>>asList(Keys.KEY_AUTHORITY_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Authority as(String alias) {
        return new Authority(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Authority as(Name alias) {
        return new Authority(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Authority rename(String name) {
        return new Authority(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Authority rename(Name name) {
        return new Authority(name, null);
    }
}
