/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.generator.Bcinvest;
import com.generator.Indexes;
import com.generator.Keys;
import com.generator.tables.records.AuthorizationRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Authorization extends TableImpl<AuthorizationRecord> {

    private static final long serialVersionUID = 287931801;

    /**
     * The reference instance of <code>bcinvest.authorization</code>
     */
    public static final Authorization AUTHORIZATION = new Authorization();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<AuthorizationRecord> getRecordType() {
        return AuthorizationRecord.class;
    }

    /**
     * The column <code>bcinvest.authorization.Name</code>.
     */
    public final TableField<AuthorizationRecord, String> NAME = createField("Name", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>bcinvest.authorization.Type</code>.
     */
    public final TableField<AuthorizationRecord, Integer> TYPE = createField("Type", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bcinvest.authorization.AccountNum</code>.
     */
    public final TableField<AuthorizationRecord, String> ACCOUNTNUM = createField("AccountNum", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>bcinvest.authorization.Password</code>.
     */
    public final TableField<AuthorizationRecord, String> PASSWORD = createField("Password", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>bcinvest.authorization.Token</code>.
     */
    public final TableField<AuthorizationRecord, String> TOKEN = createField("Token", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * Create a <code>bcinvest.authorization</code> table reference
     */
    public Authorization() {
        this(DSL.name("authorization"), null);
    }

    /**
     * Create an aliased <code>bcinvest.authorization</code> table reference
     */
    public Authorization(String alias) {
        this(DSL.name(alias), AUTHORIZATION);
    }

    /**
     * Create an aliased <code>bcinvest.authorization</code> table reference
     */
    public Authorization(Name alias) {
        this(alias, AUTHORIZATION);
    }

    private Authorization(Name alias, Table<AuthorizationRecord> aliased) {
        this(alias, aliased, null);
    }

    private Authorization(Name alias, Table<AuthorizationRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bcinvest.BCINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.AUTHORIZATION_PRIMARY, Indexes.AUTHORIZATION_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<AuthorizationRecord> getPrimaryKey() {
        return Keys.KEY_AUTHORIZATION_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<AuthorizationRecord>> getKeys() {
        return Arrays.<UniqueKey<AuthorizationRecord>>asList(Keys.KEY_AUTHORIZATION_PRIMARY, Keys.KEY_AUTHORIZATION_TOKEN);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Authorization as(String alias) {
        return new Authorization(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Authorization as(Name alias) {
        return new Authorization(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Authorization rename(String name) {
        return new Authorization(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Authorization rename(Name name) {
        return new Authorization(name, null);
    }
}
