/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.generator.Bcinvest;
import com.generator.tables.records.CreditMostFrontBlockInfoRecord;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditMostFrontBlockInfo extends TableImpl<CreditMostFrontBlockInfoRecord> {

    private static final long serialVersionUID = 1049424988;

    /**
     * The reference instance of <code>bcinvest.credit_most_front_block_info</code>
     */
    public static final CreditMostFrontBlockInfo CREDIT_MOST_FRONT_BLOCK_INFO = new CreditMostFrontBlockInfo();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CreditMostFrontBlockInfoRecord> getRecordType() {
        return CreditMostFrontBlockInfoRecord.class;
    }

    /**
     * The column <code>bcinvest.credit_most_front_block_info.this_hash</code>.
     */
    public final TableField<CreditMostFrontBlockInfoRecord, String> THIS_HASH = createField("this_hash", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_most_front_block_info.time_stamp</code>.
     */
    public final TableField<CreditMostFrontBlockInfoRecord, LocalDateTime> TIME_STAMP = createField("time_stamp", org.jooq.impl.SQLDataType.LOCALDATETIME.nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_most_front_block_info.previous_hash</code>.
     */
    public final TableField<CreditMostFrontBlockInfoRecord, String> PREVIOUS_HASH = createField("previous_hash", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_most_front_block_info.length</code>.
     */
    public final TableField<CreditMostFrontBlockInfoRecord, Long> LENGTH = createField("length", org.jooq.impl.SQLDataType.BIGINT.nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_most_front_block_info.is_main</code>.
     */
    public final TableField<CreditMostFrontBlockInfoRecord, Byte> IS_MAIN = createField("is_main", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_most_front_block_info.address</code>.
     */
    public final TableField<CreditMostFrontBlockInfoRecord, String> ADDRESS = createField("address", org.jooq.impl.SQLDataType.VARCHAR(512).nullable(false), this, "");

    /**
     * Create a <code>bcinvest.credit_most_front_block_info</code> table reference
     */
    public CreditMostFrontBlockInfo() {
        this(DSL.name("credit_most_front_block_info"), null);
    }

    /**
     * Create an aliased <code>bcinvest.credit_most_front_block_info</code> table reference
     */
    public CreditMostFrontBlockInfo(String alias) {
        this(DSL.name(alias), CREDIT_MOST_FRONT_BLOCK_INFO);
    }

    /**
     * Create an aliased <code>bcinvest.credit_most_front_block_info</code> table reference
     */
    public CreditMostFrontBlockInfo(Name alias) {
        this(alias, CREDIT_MOST_FRONT_BLOCK_INFO);
    }

    private CreditMostFrontBlockInfo(Name alias, Table<CreditMostFrontBlockInfoRecord> aliased) {
        this(alias, aliased, null);
    }

    private CreditMostFrontBlockInfo(Name alias, Table<CreditMostFrontBlockInfoRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bcinvest.BCINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditMostFrontBlockInfo as(String alias) {
        return new CreditMostFrontBlockInfo(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditMostFrontBlockInfo as(Name alias) {
        return new CreditMostFrontBlockInfo(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CreditMostFrontBlockInfo rename(String name) {
        return new CreditMostFrontBlockInfo(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CreditMostFrontBlockInfo rename(Name name) {
        return new CreditMostFrontBlockInfo(name, null);
    }
}
