/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.generator.Bcinvest;
import com.generator.tables.records.CreditMainChainViewRecord;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * VIEW
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditMainChainView extends TableImpl<CreditMainChainViewRecord> {

    private static final long serialVersionUID = -1232246808;

    /**
     * The reference instance of <code>bcinvest.credit_main_chain_view</code>
     */
    public static final CreditMainChainView CREDIT_MAIN_CHAIN_VIEW = new CreditMainChainView();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CreditMainChainViewRecord> getRecordType() {
        return CreditMainChainViewRecord.class;
    }

    /**
     * The column <code>bcinvest.credit_main_chain_view.id</code>.
     */
    public final TableField<CreditMainChainViewRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_main_chain_view.value</code>.
     */
    public final TableField<CreditMainChainViewRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_main_chain_view.variation</code>.
     */
    public final TableField<CreditMainChainViewRecord, String> VARIATION = createField("variation", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>bcinvest.credit_main_chain_view.remarks</code>.
     */
    public final TableField<CreditMainChainViewRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR(512), this, "");

    /**
     * Create a <code>bcinvest.credit_main_chain_view</code> table reference
     */
    public CreditMainChainView() {
        this(DSL.name("credit_main_chain_view"), null);
    }

    /**
     * Create an aliased <code>bcinvest.credit_main_chain_view</code> table reference
     */
    public CreditMainChainView(String alias) {
        this(DSL.name(alias), CREDIT_MAIN_CHAIN_VIEW);
    }

    /**
     * Create an aliased <code>bcinvest.credit_main_chain_view</code> table reference
     */
    public CreditMainChainView(Name alias) {
        this(alias, CREDIT_MAIN_CHAIN_VIEW);
    }

    private CreditMainChainView(Name alias, Table<CreditMainChainViewRecord> aliased) {
        this(alias, aliased, null);
    }

    private CreditMainChainView(Name alias, Table<CreditMainChainViewRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "VIEW");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bcinvest.BCINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditMainChainView as(String alias) {
        return new CreditMainChainView(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditMainChainView as(Name alias) {
        return new CreditMainChainView(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public CreditMainChainView rename(String name) {
        return new CreditMainChainView(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public CreditMainChainView rename(Name name) {
        return new CreditMainChainView(name, null);
    }
}
