/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.generator.Bcinvest;
import com.generator.Indexes;
import com.generator.Keys;
import com.generator.tables.records.CreditupdatetaskRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Identity;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Creditupdatetask extends TableImpl<CreditupdatetaskRecord> {

    private static final long serialVersionUID = -1077093648;

    /**
     * The reference instance of <code>bcinvest.CreditUpdateTask</code>
     */
    public static final Creditupdatetask CREDITUPDATETASK = new Creditupdatetask();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<CreditupdatetaskRecord> getRecordType() {
        return CreditupdatetaskRecord.class;
    }

    /**
     * The column <code>bcinvest.CreditUpdateTask.id</code>.
     */
    public final TableField<CreditupdatetaskRecord, Integer> ID = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false).identity(true), this, "");

    /**
     * The column <code>bcinvest.CreditUpdateTask.AccountNum</code>.
     */
    public final TableField<CreditupdatetaskRecord, String> ACCOUNTNUM = createField("AccountNum", org.jooq.impl.SQLDataType.VARCHAR(128), this, "");

    /**
     * The column <code>bcinvest.CreditUpdateTask.previousCredit</code>.
     */
    public final TableField<CreditupdatetaskRecord, Integer> PREVIOUSCREDIT = createField("previousCredit", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bcinvest.CreditUpdateTask.delta</code>.
     */
    public final TableField<CreditupdatetaskRecord, Integer> DELTA = createField("delta", org.jooq.impl.SQLDataType.INTEGER, this, "");

    /**
     * The column <code>bcinvest.CreditUpdateTask.state</code>.
     */
    public final TableField<CreditupdatetaskRecord, String> STATE = createField("state", org.jooq.impl.SQLDataType.VARCHAR(36), this, "");

    /**
     * Create a <code>bcinvest.CreditUpdateTask</code> table reference
     */
    public Creditupdatetask() {
        this(DSL.name("CreditUpdateTask"), null);
    }

    /**
     * Create an aliased <code>bcinvest.CreditUpdateTask</code> table reference
     */
    public Creditupdatetask(String alias) {
        this(DSL.name(alias), CREDITUPDATETASK);
    }

    /**
     * Create an aliased <code>bcinvest.CreditUpdateTask</code> table reference
     */
    public Creditupdatetask(Name alias) {
        this(alias, CREDITUPDATETASK);
    }

    private Creditupdatetask(Name alias, Table<CreditupdatetaskRecord> aliased) {
        this(alias, aliased, null);
    }

    private Creditupdatetask(Name alias, Table<CreditupdatetaskRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bcinvest.BCINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.CREDITUPDATETASK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Identity<CreditupdatetaskRecord, Integer> getIdentity() {
        return Keys.IDENTITY_CREDITUPDATETASK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<CreditupdatetaskRecord> getPrimaryKey() {
        return Keys.KEY_CREDITUPDATETASK_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<CreditupdatetaskRecord>> getKeys() {
        return Arrays.<UniqueKey<CreditupdatetaskRecord>>asList(Keys.KEY_CREDITUPDATETASK_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Creditupdatetask as(String alias) {
        return new Creditupdatetask(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Creditupdatetask as(Name alias) {
        return new Creditupdatetask(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public Creditupdatetask rename(String name) {
        return new Creditupdatetask(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public Creditupdatetask rename(Name name) {
        return new Creditupdatetask(name, null);
    }
}
