/*
 * This file is generated by jOOQ.
*/
package com.generator.tables;


import com.generator.Bcinvest;
import com.generator.Indexes;
import com.generator.Keys;
import com.generator.tables.records.GuarantyDataRecord;

import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.ForeignKey;
import org.jooq.Index;
import org.jooq.Name;
import org.jooq.Schema;
import org.jooq.Table;
import org.jooq.TableField;
import org.jooq.UniqueKey;
import org.jooq.impl.DSL;
import org.jooq.impl.TableImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuarantyData extends TableImpl<GuarantyDataRecord> {

    private static final long serialVersionUID = 378789561;

    /**
     * The reference instance of <code>bcinvest.guaranty_data</code>
     */
    public static final GuarantyData GUARANTY_DATA = new GuarantyData();

    /**
     * The class holding records for this type
     */
    @Override
    public Class<GuarantyDataRecord> getRecordType() {
        return GuarantyDataRecord.class;
    }

    /**
     * The column <code>bcinvest.guaranty_data.block_hash</code>.
     */
    public final TableField<GuarantyDataRecord, String> BLOCK_HASH = createField("block_hash", org.jooq.impl.SQLDataType.VARCHAR(64).nullable(false), this, "");

    /**
     * The column <code>bcinvest.guaranty_data.id</code>.
     */
    public final TableField<GuarantyDataRecord, String> ID = createField("id", org.jooq.impl.SQLDataType.VARCHAR(256).nullable(false), this, "");

    /**
     * The column <code>bcinvest.guaranty_data.variation</code>.
     */
    public final TableField<GuarantyDataRecord, String> VARIATION = createField("variation", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>bcinvest.guaranty_data.value</code>.
     */
    public final TableField<GuarantyDataRecord, String> VALUE = createField("value", org.jooq.impl.SQLDataType.VARCHAR(128).nullable(false), this, "");

    /**
     * The column <code>bcinvest.guaranty_data.remarks</code>.
     */
    public final TableField<GuarantyDataRecord, String> REMARKS = createField("remarks", org.jooq.impl.SQLDataType.VARCHAR(512), this, "");

    /**
     * Create a <code>bcinvest.guaranty_data</code> table reference
     */
    public GuarantyData() {
        this(DSL.name("guaranty_data"), null);
    }

    /**
     * Create an aliased <code>bcinvest.guaranty_data</code> table reference
     */
    public GuarantyData(String alias) {
        this(DSL.name(alias), GUARANTY_DATA);
    }

    /**
     * Create an aliased <code>bcinvest.guaranty_data</code> table reference
     */
    public GuarantyData(Name alias) {
        this(alias, GUARANTY_DATA);
    }

    private GuarantyData(Name alias, Table<GuarantyDataRecord> aliased) {
        this(alias, aliased, null);
    }

    private GuarantyData(Name alias, Table<GuarantyDataRecord> aliased, Field<?>[] parameters) {
        super(alias, null, aliased, parameters, "");
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Schema getSchema() {
        return Bcinvest.BCINVEST;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<Index> getIndexes() {
        return Arrays.<Index>asList(Indexes.GUARANTY_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public UniqueKey<GuarantyDataRecord> getPrimaryKey() {
        return Keys.KEY_GUARANTY_DATA_PRIMARY;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<UniqueKey<GuarantyDataRecord>> getKeys() {
        return Arrays.<UniqueKey<GuarantyDataRecord>>asList(Keys.KEY_GUARANTY_DATA_PRIMARY);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public List<ForeignKey<GuarantyDataRecord, ?>> getReferences() {
        return Arrays.<ForeignKey<GuarantyDataRecord, ?>>asList(Keys.GUARANTY_DATA_CHAIN_THIS_HASH_FK);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyData as(String alias) {
        return new GuarantyData(DSL.name(alias), this);
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyData as(Name alias) {
        return new GuarantyData(alias, this);
    }

    /**
     * Rename this table
     */
    @Override
    public GuarantyData rename(String name) {
        return new GuarantyData(DSL.name(name), null);
    }

    /**
     * Rename this table
     */
    @Override
    public GuarantyData rename(Name name) {
        return new GuarantyData(name, null);
    }
}
