/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Accesstoken;
import com.generator.tables.Authority;
import com.generator.tables.Bankoperator;
import com.generator.tables.Company;
import com.generator.tables.Guaranty;
import com.generator.tables.Protocol;
import com.generator.tables.Report;

import java.util.ArrayList;
import java.util.Arrays;
import java.util.List;

import javax.annotation.Generated;

import org.jooq.Catalog;
import org.jooq.Table;
import org.jooq.impl.SchemaImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Bcinvest extends SchemaImpl {

    private static final long serialVersionUID = -1986262471;

    /**
     * The reference instance of <code>bcinvest</code>
     */
    public static final Bcinvest BCINVEST = new Bcinvest();

    /**
     * The table <code>bcinvest.AccessToken</code>.
     */
    public final Accesstoken ACCESSTOKEN = com.generator.tables.Accesstoken.ACCESSTOKEN;

    /**
     * The table <code>bcinvest.Authority</code>.
     */
    public final Authority AUTHORITY = com.generator.tables.Authority.AUTHORITY;

    /**
     * The table <code>bcinvest.BankOperator</code>.
     */
    public final Bankoperator BANKOPERATOR = com.generator.tables.Bankoperator.BANKOPERATOR;

    /**
     * The table <code>bcinvest.Company</code>.
     */
    public final Company COMPANY = com.generator.tables.Company.COMPANY;

    /**
     * The table <code>bcinvest.Guaranty</code>.
     */
    public final Guaranty GUARANTY = com.generator.tables.Guaranty.GUARANTY;

    /**
     * The table <code>bcinvest.Protocol</code>.
     */
    public final Protocol PROTOCOL = com.generator.tables.Protocol.PROTOCOL;

    /**
     * The table <code>bcinvest.Report</code>.
     */
    public final Report REPORT = com.generator.tables.Report.REPORT;

    /**
     * No further instances allowed
     */
    private Bcinvest() {
        super("bcinvest", null);
    }


    /**
     * {@inheritDoc}
     */
    @Override
    public Catalog getCatalog() {
        return DefaultCatalog.DEFAULT_CATALOG;
    }

    @Override
    public final List<Table<?>> getTables() {
        List result = new ArrayList();
        result.addAll(getTables0());
        return result;
    }

    private final List<Table<?>> getTables0() {
        return Arrays.<Table<?>>asList(
            Accesstoken.ACCESSTOKEN,
            Authority.AUTHORITY,
            Bankoperator.BANKOPERATOR,
            Company.COMPANY,
            Guaranty.GUARANTY,
            Protocol.PROTOCOL,
            Report.REPORT);
    }
}
