/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Accesstoken;
import com.generator.tables.Authority;
import com.generator.tables.Bankoperator;
import com.generator.tables.Company;
import com.generator.tables.Guaranty;
import com.generator.tables.Protocol;
import com.generator.tables.Report;

import javax.annotation.Generated;

import org.jooq.Index;
import org.jooq.OrderField;
import org.jooq.impl.Internal;


/**
 * A class modelling indexes of tables of the <code>bcinvest</code> schema.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Indexes {

    // -------------------------------------------------------------------------
    // INDEX definitions
    // -------------------------------------------------------------------------

    public static final Index ACCESSTOKEN_PRIMARY = Indexes0.ACCESSTOKEN_PRIMARY;
    public static final Index AUTHORITY_PRIMARY = Indexes0.AUTHORITY_PRIMARY;
    public static final Index BANKOPERATOR_PRIMARY = Indexes0.BANKOPERATOR_PRIMARY;
    public static final Index COMPANY_EMAIL_UNIQUE = Indexes0.COMPANY_EMAIL_UNIQUE;
    public static final Index COMPANY_PRIMARY = Indexes0.COMPANY_PRIMARY;
    public static final Index GUARANTY_PRIMARY = Indexes0.GUARANTY_PRIMARY;
    public static final Index PROTOCOL_PRIMARY = Indexes0.PROTOCOL_PRIMARY;
    public static final Index REPORT_PRIMARY = Indexes0.REPORT_PRIMARY;

    // -------------------------------------------------------------------------
    // [#1459] distribute members to avoid static initialisers > 64kb
    // -------------------------------------------------------------------------

    private static class Indexes0 {
        public static Index ACCESSTOKEN_PRIMARY = Internal.createIndex("PRIMARY", Accesstoken.ACCESSTOKEN, new OrderField[] { Accesstoken.ACCESSTOKEN.ID }, true);
        public static Index AUTHORITY_PRIMARY = Internal.createIndex("PRIMARY", Authority.AUTHORITY, new OrderField[] { Authority.AUTHORITY.ID }, true);
        public static Index BANKOPERATOR_PRIMARY = Internal.createIndex("PRIMARY", Bankoperator.BANKOPERATOR, new OrderField[] { Bankoperator.BANKOPERATOR.ID }, true);
        public static Index COMPANY_EMAIL_UNIQUE = Internal.createIndex("email_UNIQUE", Company.COMPANY, new OrderField[] { Company.COMPANY.EMAIL }, true);
        public static Index COMPANY_PRIMARY = Internal.createIndex("PRIMARY", Company.COMPANY, new OrderField[] { Company.COMPANY.ID }, true);
        public static Index GUARANTY_PRIMARY = Internal.createIndex("PRIMARY", Guaranty.GUARANTY, new OrderField[] { Guaranty.GUARANTY.ID }, true);
        public static Index PROTOCOL_PRIMARY = Internal.createIndex("PRIMARY", Protocol.PROTOCOL, new OrderField[] { Protocol.PROTOCOL.ID }, true);
        public static Index REPORT_PRIMARY = Internal.createIndex("PRIMARY", Report.REPORT, new OrderField[] { Report.REPORT.ID }, true);
    }
}
