/*
 * This file is generated by jOOQ.
*/
package com.generator;


import com.generator.tables.Accesstoken;
import com.generator.tables.Authority;
import com.generator.tables.Bankoperator;
import com.generator.tables.Company;
import com.generator.tables.Guaranty;
import com.generator.tables.Protocol;
import com.generator.tables.Report;

import javax.annotation.Generated;


/**
 * Convenience access to all tables in bcinvest
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

    /**
     * The table <code>bcinvest.AccessToken</code>.
     */
    public static final Accesstoken ACCESSTOKEN = com.generator.tables.Accesstoken.ACCESSTOKEN;

    /**
     * The table <code>bcinvest.Authority</code>.
     */
    public static final Authority AUTHORITY = com.generator.tables.Authority.AUTHORITY;

    /**
     * The table <code>bcinvest.BankOperator</code>.
     */
    public static final Bankoperator BANKOPERATOR = com.generator.tables.Bankoperator.BANKOPERATOR;

    /**
     * The table <code>bcinvest.Company</code>.
     */
    public static final Company COMPANY = com.generator.tables.Company.COMPANY;

    /**
     * The table <code>bcinvest.Guaranty</code>.
     */
    public static final Guaranty GUARANTY = com.generator.tables.Guaranty.GUARANTY;

    /**
     * The table <code>bcinvest.Protocol</code>.
     */
    public static final Protocol PROTOCOL = com.generator.tables.Protocol.PROTOCOL;

    /**
     * The table <code>bcinvest.Report</code>.
     */
    public static final Report REPORT = com.generator.tables.Report.REPORT;
}
