/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.generator.tables.Accesstoken;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record4;
import org.jooq.Row4;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccesstokenRecord extends UpdatableRecordImpl<AccesstokenRecord> implements Record4<Integer, String, String, String> {

    private static final long serialVersionUID = -410709358;

    /**
     * Setter for <code>bcinvest.AccessToken.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcinvest.AccessToken.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bcinvest.AccessToken.value</code>.
     */
    public void setValue(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcinvest.AccessToken.value</code>.
     */
    public String getValue() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcinvest.AccessToken.expire_time</code>.
     */
    public void setExpireTime(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcinvest.AccessToken.expire_time</code>.
     */
    public String getExpireTime() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcinvest.AccessToken.company_id</code>.
     */
    public void setCompanyId(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcinvest.AccessToken.company_id</code>.
     */
    public String getCompanyId() {
        return (String) get(3);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record4 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> fieldsRow() {
        return (Row4) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row4<Integer, String, String, String> valuesRow() {
        return (Row4) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Accesstoken.ACCESSTOKEN.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Accesstoken.ACCESSTOKEN.VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Accesstoken.ACCESSTOKEN.EXPIRE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Accesstoken.ACCESSTOKEN.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getExpireTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccesstokenRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccesstokenRecord value2(String value) {
        setValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccesstokenRecord value3(String value) {
        setExpireTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccesstokenRecord value4(String value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public AccesstokenRecord values(Integer value1, String value2, String value3, String value4) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached AccesstokenRecord
     */
    public AccesstokenRecord() {
        super(Accesstoken.ACCESSTOKEN);
    }

    /**
     * Create a detached, initialised AccesstokenRecord
     */
    public AccesstokenRecord(Integer id, String value, String expireTime, String companyId) {
        super(Accesstoken.ACCESSTOKEN);

        set(0, id);
        set(1, value);
        set(2, expireTime);
        set(3, companyId);
    }
}
