/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.generator.tables.CreditChain;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class CreditChainRecord extends UpdatableRecordImpl<CreditChainRecord> implements Record6<String, LocalDateTime, String, Long, Byte, String> {

    private static final long serialVersionUID = 1096675274;

    /**
     * Setter for <code>bcinvest.credit_chain.this_hash</code>.
     */
    public void setThisHash(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcinvest.credit_chain.this_hash</code>.
     */
    public String getThisHash() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bcinvest.credit_chain.time_stamp</code>.
     */
    public void setTimeStamp(LocalDateTime value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcinvest.credit_chain.time_stamp</code>.
     */
    public LocalDateTime getTimeStamp() {
        return (LocalDateTime) get(1);
    }

    /**
     * Setter for <code>bcinvest.credit_chain.previous_hash</code>.
     */
    public void setPreviousHash(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcinvest.credit_chain.previous_hash</code>.
     */
    public String getPreviousHash() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcinvest.credit_chain.length</code>.
     */
    public void setLength(Long value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcinvest.credit_chain.length</code>.
     */
    public Long getLength() {
        return (Long) get(3);
    }

    /**
     * Setter for <code>bcinvest.credit_chain.is_main</code>.
     */
    public void setIsMain(Byte value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcinvest.credit_chain.is_main</code>.
     */
    public Byte getIsMain() {
        return (Byte) get(4);
    }

    /**
     * Setter for <code>bcinvest.credit_chain.address</code>.
     */
    public void setAddress(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcinvest.credit_chain.address</code>.
     */
    public String getAddress() {
        return (String) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, LocalDateTime, String, Long, Byte, String> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row6<String, LocalDateTime, String, Long, Byte, String> valuesRow() {
        return (Row6) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return CreditChain.CREDIT_CHAIN.THIS_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field2() {
        return CreditChain.CREDIT_CHAIN.TIME_STAMP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return CreditChain.CREDIT_CHAIN.PREVIOUS_HASH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field4() {
        return CreditChain.CREDIT_CHAIN.LENGTH;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field5() {
        return CreditChain.CREDIT_CHAIN.IS_MAIN;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return CreditChain.CREDIT_CHAIN.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getThisHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component2() {
        return getTimeStamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getPreviousHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component4() {
        return getLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component5() {
        return getIsMain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getThisHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value2() {
        return getTimeStamp();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getPreviousHash();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value4() {
        return getLength();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value5() {
        return getIsMain();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditChainRecord value1(String value) {
        setThisHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditChainRecord value2(LocalDateTime value) {
        setTimeStamp(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditChainRecord value3(String value) {
        setPreviousHash(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditChainRecord value4(Long value) {
        setLength(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditChainRecord value5(Byte value) {
        setIsMain(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditChainRecord value6(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public CreditChainRecord values(String value1, LocalDateTime value2, String value3, Long value4, Byte value5, String value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached CreditChainRecord
     */
    public CreditChainRecord() {
        super(CreditChain.CREDIT_CHAIN);
    }

    /**
     * Create a detached, initialised CreditChainRecord
     */
    public CreditChainRecord(String thisHash, LocalDateTime timeStamp, String previousHash, Long length, Byte isMain, String address) {
        super(CreditChain.CREDIT_CHAIN);

        set(0, thisHash);
        set(1, timeStamp);
        set(2, previousHash);
        set(3, length);
        set(4, isMain);
        set(5, address);
    }
}
