/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.generator.tables.Guaranty;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record16;
import org.jooq.Row16;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class GuarantyRecord extends UpdatableRecordImpl<GuarantyRecord> implements Record16<Integer, String, String, String, String, String, String, Integer, String, String, String, Integer, String, String, String, Byte> {

    private static final long serialVersionUID = 193241215;

    /**
     * Setter for <code>bcinvest.Guaranty.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.company_id</code>.
     */
    public void setCompanyId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.company_id</code>.
     */
    public String getCompanyId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.state</code>.
     */
    public void setState(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.state</code>.
     */
    public String getState() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.right_scope</code>.
     */
    public void setRightScope(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.right_scope</code>.
     */
    public String getRightScope() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.owner_name</code>.
     */
    public void setOwnerName(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.owner_name</code>.
     */
    public String getOwnerName() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.report_id</code>.
     */
    public void setReportId(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.report_id</code>.
     */
    public String getReportId() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.type</code>. Machine,home,land
     */
    public void setType(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.type</code>. Machine,home,land
     */
    public String getType() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.evaluate_value</code>.
     */
    public void setEvaluateValue(Integer value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.evaluate_value</code>.
     */
    public Integer getEvaluateValue() {
        return (Integer) get(7);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.name</code>.
     */
    public void setName(String value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.name</code>.
     */
    public String getName() {
        return (String) get(8);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.producer</code>. machine
     */
    public void setProducer(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.producer</code>. machine
     */
    public String getProducer() {
        return (String) get(9);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.model</code>. Machine
     */
    public void setModel(String value) {
        set(10, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.model</code>. Machine
     */
    public String getModel() {
        return (String) get(10);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.used_days</code>. machine
     */
    public void setUsedDays(Integer value) {
        set(11, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.used_days</code>. machine
     */
    public Integer getUsedDays() {
        return (Integer) get(11);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.address</code>. Land,home
     */
    public void setAddress(String value) {
        set(12, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.address</code>. Land,home
     */
    public String getAddress() {
        return (String) get(12);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.area</code>. area
     */
    public void setArea(String value) {
        set(13, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.area</code>. area
     */
    public String getArea() {
        return (String) get(13);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.zip</code>. Home
     */
    public void setZip(String value) {
        set(14, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.zip</code>. Home
     */
    public String getZip() {
        return (String) get(14);
    }

    /**
     * Setter for <code>bcinvest.Guaranty.lock</code>.
     */
    public void setLock(Byte value) {
        set(15, value);
    }

    /**
     * Getter for <code>bcinvest.Guaranty.lock</code>.
     */
    public Byte getLock() {
        return (Byte) get(15);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record16 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, String, String, Integer, String, String, String, Integer, String, String, String, Byte> fieldsRow() {
        return (Row16) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row16<Integer, String, String, String, String, String, String, Integer, String, String, String, Integer, String, String, String, Byte> valuesRow() {
        return (Row16) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Guaranty.GUARANTY.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Guaranty.GUARANTY.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Guaranty.GUARANTY.STATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Guaranty.GUARANTY.RIGHT_SCOPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Guaranty.GUARANTY.OWNER_NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Guaranty.GUARANTY.REPORT_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Guaranty.GUARANTY.TYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field8() {
        return Guaranty.GUARANTY.EVALUATE_VALUE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field9() {
        return Guaranty.GUARANTY.NAME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Guaranty.GUARANTY.PRODUCER;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field11() {
        return Guaranty.GUARANTY.MODEL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field12() {
        return Guaranty.GUARANTY.USED_DAYS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field13() {
        return Guaranty.GUARANTY.ADDRESS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field14() {
        return Guaranty.GUARANTY.AREA;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field15() {
        return Guaranty.GUARANTY.ZIP;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field16() {
        return Guaranty.GUARANTY.LOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getRightScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getOwnerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getReportId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component8() {
        return getEvaluateValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component9() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getProducer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component11() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component12() {
        return getUsedDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component13() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component14() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component15() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component16() {
        return getLock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getState();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getRightScope();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getOwnerName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getReportId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getType();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value8() {
        return getEvaluateValue();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value9() {
        return getName();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getProducer();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value11() {
        return getModel();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value12() {
        return getUsedDays();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value13() {
        return getAddress();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value14() {
        return getArea();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value15() {
        return getZip();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value16() {
        return getLock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value2(String value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value3(String value) {
        setState(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value4(String value) {
        setRightScope(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value5(String value) {
        setOwnerName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value6(String value) {
        setReportId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value7(String value) {
        setType(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value8(Integer value) {
        setEvaluateValue(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value9(String value) {
        setName(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value10(String value) {
        setProducer(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value11(String value) {
        setModel(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value12(Integer value) {
        setUsedDays(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value13(String value) {
        setAddress(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value14(String value) {
        setArea(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value15(String value) {
        setZip(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord value16(Byte value) {
        setLock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public GuarantyRecord values(Integer value1, String value2, String value3, String value4, String value5, String value6, String value7, Integer value8, String value9, String value10, String value11, Integer value12, String value13, String value14, String value15, Byte value16) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        value11(value11);
        value12(value12);
        value13(value13);
        value14(value14);
        value15(value15);
        value16(value16);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached GuarantyRecord
     */
    public GuarantyRecord() {
        super(Guaranty.GUARANTY);
    }

    /**
     * Create a detached, initialised GuarantyRecord
     */
    public GuarantyRecord(Integer id, String companyId, String state, String rightScope, String ownerName, String reportId, String type, Integer evaluateValue, String name, String producer, String model, Integer usedDays, String address, String area, String zip, Byte lock) {
        super(Guaranty.GUARANTY);

        set(0, id);
        set(1, companyId);
        set(2, state);
        set(3, rightScope);
        set(4, ownerName);
        set(5, reportId);
        set(6, type);
        set(7, evaluateValue);
        set(8, name);
        set(9, producer);
        set(10, model);
        set(11, usedDays);
        set(12, address);
        set(13, area);
        set(14, zip);
        set(15, lock);
    }
}
