/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.generator.tables.Protocol;

import java.time.LocalDate;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record7;
import org.jooq.Row7;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProtocolRecord extends UpdatableRecordImpl<ProtocolRecord> implements Record7<Integer, Integer, LocalDate, String, LocalDate, String, String> {

    private static final long serialVersionUID = -750894311;

    /**
     * Setter for <code>bcinvest.Protocol.ProtocolId</code>.
     */
    public void setProtocolid(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.ProtocolId</code>.
     */
    public Integer getProtocolid() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bcinvest.Protocol.GurantyId</code>.
     */
    public void setGurantyid(Integer value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.GurantyId</code>.
     */
    public Integer getGurantyid() {
        return (Integer) get(1);
    }

    /**
     * Setter for <code>bcinvest.Protocol.StartDate</code>.
     */
    public void setStartdate(LocalDate value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.StartDate</code>.
     */
    public LocalDate getStartdate() {
        return (LocalDate) get(2);
    }

    /**
     * Setter for <code>bcinvest.Protocol.Duration</code>.
     */
    public void setDuration(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.Duration</code>.
     */
    public String getDuration() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bcinvest.Protocol.EndDate</code>.
     */
    public void setEnddate(LocalDate value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.EndDate</code>.
     */
    public LocalDate getEnddate() {
        return (LocalDate) get(4);
    }

    /**
     * Setter for <code>bcinvest.Protocol.Message</code>.
     */
    public void setMessage(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.Message</code>.
     */
    public String getMessage() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bcinvest.Protocol.Condition</code>.
     */
    public void setCondition(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.Condition</code>.
     */
    public String getCondition() {
        return (String) get(6);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record7 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, LocalDate, String, LocalDate, String, String> fieldsRow() {
        return (Row7) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row7<Integer, Integer, LocalDate, String, LocalDate, String, String> valuesRow() {
        return (Row7) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Protocol.PROTOCOL.PROTOCOLID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field2() {
        return Protocol.PROTOCOL.GURANTYID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field3() {
        return Protocol.PROTOCOL.STARTDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Protocol.PROTOCOL.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDate> field5() {
        return Protocol.PROTOCOL.ENDDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Protocol.PROTOCOL.MESSAGE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Protocol.PROTOCOL.CONDITION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getProtocolid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component2() {
        return getGurantyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component3() {
        return getStartdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate component5() {
        return getEnddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getCondition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getProtocolid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value2() {
        return getGurantyid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value3() {
        return getStartdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDate value5() {
        return getEnddate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getMessage();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getCondition();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value1(Integer value) {
        setProtocolid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value2(Integer value) {
        setGurantyid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value3(LocalDate value) {
        setStartdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value4(String value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value5(LocalDate value) {
        setEnddate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value6(String value) {
        setMessage(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value7(String value) {
        setCondition(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord values(Integer value1, Integer value2, LocalDate value3, String value4, LocalDate value5, String value6, String value7) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProtocolRecord
     */
    public ProtocolRecord() {
        super(Protocol.PROTOCOL);
    }

    /**
     * Create a detached, initialised ProtocolRecord
     */
    public ProtocolRecord(Integer protocolid, Integer gurantyid, LocalDate startdate, String duration, LocalDate enddate, String message, String condition) {
        super(Protocol.PROTOCOL);

        set(0, protocolid);
        set(1, gurantyid);
        set(2, startdate);
        set(3, duration);
        set(4, enddate);
        set(5, message);
        set(6, condition);
    }
}
