/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.generator.tables.Protocol;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record9;
import org.jooq.Row9;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ProtocolRecord extends UpdatableRecordImpl<ProtocolRecord> implements Record9<Integer, String, String, LocalDateTime, String, String, String, String, Byte> {

    private static final long serialVersionUID = -263184954;

    /**
     * Setter for <code>bcinvest.Protocol.id</code>.
     */
    public void setId(Integer value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.id</code>.
     */
    public Integer getId() {
        return (Integer) get(0);
    }

    /**
     * Setter for <code>bcinvest.Protocol.company_id</code>.
     */
    public void setCompanyId(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.company_id</code>.
     */
    public String getCompanyId() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcinvest.Protocol.guaranty_id</code>.
     */
    public void setGuarantyId(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.guaranty_id</code>.
     */
    public String getGuarantyId() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcinvest.Protocol.create_time</code>.
     */
    public void setCreateTime(LocalDateTime value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.create_time</code>.
     */
    public LocalDateTime getCreateTime() {
        return (LocalDateTime) get(3);
    }

    /**
     * Setter for <code>bcinvest.Protocol.duration</code>.
     */
    public void setDuration(String value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.duration</code>.
     */
    public String getDuration() {
        return (String) get(4);
    }

    /**
     * Setter for <code>bcinvest.Protocol.end_time</code>.
     */
    public void setEndTime(String value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.end_time</code>.
     */
    public String getEndTime() {
        return (String) get(5);
    }

    /**
     * Setter for <code>bcinvest.Protocol.content</code>.
     */
    public void setContent(String value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.content</code>.
     */
    public String getContent() {
        return (String) get(6);
    }

    /**
     * Setter for <code>bcinvest.Protocol.status</code>.
     */
    public void setStatus(String value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.status</code>.
     */
    public String getStatus() {
        return (String) get(7);
    }

    /**
     * Setter for <code>bcinvest.Protocol.lock</code>.
     */
    public void setLock(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcinvest.Protocol.lock</code>.
     */
    public Byte getLock() {
        return (Byte) get(8);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<Integer> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record9 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, LocalDateTime, String, String, String, String, Byte> fieldsRow() {
        return (Row9) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row9<Integer, String, String, LocalDateTime, String, String, String, String, Byte> valuesRow() {
        return (Row9) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field1() {
        return Protocol.PROTOCOL.ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Protocol.PROTOCOL.COMPANY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Protocol.PROTOCOL.GUARANTY_ID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field4() {
        return Protocol.PROTOCOL.CREATE_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field5() {
        return Protocol.PROTOCOL.DURATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field6() {
        return Protocol.PROTOCOL.END_TIME;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field7() {
        return Protocol.PROTOCOL.CONTENT;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field8() {
        return Protocol.PROTOCOL.STATUS;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Protocol.PROTOCOL.LOCK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getGuarantyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component5() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component6() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component7() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getLock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value1() {
        return getId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getCompanyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getGuarantyId();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value4() {
        return getCreateTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value5() {
        return getDuration();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value6() {
        return getEndTime();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value7() {
        return getContent();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value8() {
        return getStatus();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getLock();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value1(Integer value) {
        setId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value2(String value) {
        setCompanyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value3(String value) {
        setGuarantyId(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value4(LocalDateTime value) {
        setCreateTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value5(String value) {
        setDuration(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value6(String value) {
        setEndTime(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value7(String value) {
        setContent(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value8(String value) {
        setStatus(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord value9(Byte value) {
        setLock(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public ProtocolRecord values(Integer value1, String value2, String value3, LocalDateTime value4, String value5, String value6, String value7, String value8, Byte value9) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached ProtocolRecord
     */
    public ProtocolRecord() {
        super(Protocol.PROTOCOL);
    }

    /**
     * Create a detached, initialised ProtocolRecord
     */
    public ProtocolRecord(Integer id, String companyId, String guarantyId, LocalDateTime createTime, String duration, String endTime, String content, String status, Byte lock) {
        super(Protocol.PROTOCOL);

        set(0, id);
        set(1, companyId);
        set(2, guarantyId);
        set(3, createTime);
        set(4, duration);
        set(5, endTime);
        set(6, content);
        set(7, status);
        set(8, lock);
    }
}
