/*
 * This file is generated by jOOQ.
*/
package com.generator.tables.records;


import com.generator.tables.Securitiesinformation;

import java.time.LocalDateTime;

import javax.annotation.Generated;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record10;
import org.jooq.Row10;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@Generated(
    value = {
        "http://www.jooq.org",
        "jOOQ version:3.10.7"
    },
    comments = "This class is generated by jOOQ"
)
@SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class SecuritiesinformationRecord extends UpdatableRecordImpl<SecuritiesinformationRecord> implements Record10<String, String, String, String, Long, Integer, LocalDateTime, Long, Byte, String> {

    private static final long serialVersionUID = 1887985979;

    /**
     * Setter for <code>bcinvest.securitiesinformation.AccountNum</code>.
     */
    public void setAccountnum(String value) {
        set(0, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.AccountNum</code>.
     */
    public String getAccountnum() {
        return (String) get(0);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.StockCode</code>.
     */
    public void setStockcode(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.StockCode</code>.
     */
    public String getStockcode() {
        return (String) get(1);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.ListedApproval</code>.
     */
    public void setListedapproval(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.ListedApproval</code>.
     */
    public String getListedapproval() {
        return (String) get(2);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.StockAbbr</code>.
     */
    public void setStockabbr(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.StockAbbr</code>.
     */
    public String getStockabbr() {
        return (String) get(3);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.IssuePrice</code>.
     */
    public void setIssueprice(Long value) {
        set(4, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.IssuePrice</code>.
     */
    public Long getIssueprice() {
        return (Long) get(4);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.StockType</code>.
     */
    public void setStocktype(Integer value) {
        set(5, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.StockType</code>.
     */
    public Integer getStocktype() {
        return (Integer) get(5);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.LaunchDate</code>.
     */
    public void setLaunchdate(LocalDateTime value) {
        set(6, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.LaunchDate</code>.
     */
    public LocalDateTime getLaunchdate() {
        return (LocalDateTime) get(6);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.Circulation</code>.
     */
    public void setCirculation(Long value) {
        set(7, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.Circulation</code>.
     */
    public Long getCirculation() {
        return (Long) get(7);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.IsValid</code>.
     */
    public void setIsvalid(Byte value) {
        set(8, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.IsValid</code>.
     */
    public Byte getIsvalid() {
        return (Byte) get(8);
    }

    /**
     * Setter for <code>bcinvest.securitiesinformation.Remark</code>.
     */
    public void setRemark(String value) {
        set(9, value);
    }

    /**
     * Getter for <code>bcinvest.securitiesinformation.Remark</code>.
     */
    public String getRemark() {
        return (String) get(9);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Record1<String> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record10 type implementation
    // -------------------------------------------------------------------------

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, Long, Integer, LocalDateTime, Long, Byte, String> fieldsRow() {
        return (Row10) super.fieldsRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Row10<String, String, String, String, Long, Integer, LocalDateTime, Long, Byte, String> valuesRow() {
        return (Row10) super.valuesRow();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field1() {
        return Securitiesinformation.SECURITIESINFORMATION.ACCOUNTNUM;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field2() {
        return Securitiesinformation.SECURITIESINFORMATION.STOCKCODE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field3() {
        return Securitiesinformation.SECURITIESINFORMATION.LISTEDAPPROVAL;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field4() {
        return Securitiesinformation.SECURITIESINFORMATION.STOCKABBR;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field5() {
        return Securitiesinformation.SECURITIESINFORMATION.ISSUEPRICE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Integer> field6() {
        return Securitiesinformation.SECURITIESINFORMATION.STOCKTYPE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<LocalDateTime> field7() {
        return Securitiesinformation.SECURITIESINFORMATION.LAUNCHDATE;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Long> field8() {
        return Securitiesinformation.SECURITIESINFORMATION.CIRCULATION;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<Byte> field9() {
        return Securitiesinformation.SECURITIESINFORMATION.ISVALID;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Field<String> field10() {
        return Securitiesinformation.SECURITIESINFORMATION.REMARK;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component1() {
        return getAccountnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component2() {
        return getStockcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component3() {
        return getListedapproval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component4() {
        return getStockabbr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component5() {
        return getIssueprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer component6() {
        return getStocktype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime component7() {
        return getLaunchdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long component8() {
        return getCirculation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte component9() {
        return getIsvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String component10() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value1() {
        return getAccountnum();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value2() {
        return getStockcode();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value3() {
        return getListedapproval();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value4() {
        return getStockabbr();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value5() {
        return getIssueprice();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Integer value6() {
        return getStocktype();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public LocalDateTime value7() {
        return getLaunchdate();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Long value8() {
        return getCirculation();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public Byte value9() {
        return getIsvalid();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public String value10() {
        return getRemark();
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value1(String value) {
        setAccountnum(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value2(String value) {
        setStockcode(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value3(String value) {
        setListedapproval(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value4(String value) {
        setStockabbr(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value5(Long value) {
        setIssueprice(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value6(Integer value) {
        setStocktype(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value7(LocalDateTime value) {
        setLaunchdate(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value8(Long value) {
        setCirculation(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value9(Byte value) {
        setIsvalid(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord value10(String value) {
        setRemark(value);
        return this;
    }

    /**
     * {@inheritDoc}
     */
    @Override
    public SecuritiesinformationRecord values(String value1, String value2, String value3, String value4, Long value5, Integer value6, LocalDateTime value7, Long value8, Byte value9, String value10) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        value7(value7);
        value8(value8);
        value9(value9);
        value10(value10);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached SecuritiesinformationRecord
     */
    public SecuritiesinformationRecord() {
        super(Securitiesinformation.SECURITIESINFORMATION);
    }

    /**
     * Create a detached, initialised SecuritiesinformationRecord
     */
    public SecuritiesinformationRecord(String accountnum, String stockcode, String listedapproval, String stockabbr, Long issueprice, Integer stocktype, LocalDateTime launchdate, Long circulation, Byte isvalid, String remark) {
        super(Securitiesinformation.SECURITIESINFORMATION);

        set(0, accountnum);
        set(1, stockcode);
        set(2, listedapproval);
        set(3, stockabbr);
        set(4, issueprice);
        set(5, stocktype);
        set(6, launchdate);
        set(7, circulation);
        set(8, isvalid);
        set(9, remark);
    }
}
